number = {'Two', 'Three', 'One'}
print("The set is: ",number)
print("Adding elements to the set")
number.add("Five")
number.add("Seven")
print("--------------"*4)
print("Adding multiple elements using Update()")
number.update(["Six","Eight","Nine"])
print(number)
print("--------------"*4)
print("removing the Elements using 'discard()'")
number.discard("Eight")
print(number)
print("--------------"*4)
print("removing the Elements using 'remove()'")
number.remove("Nine")
print(number)
print("--------------"*4)
print("Removing all the items from the set...")
number.clear()
print(number)
